spring:
  application:
    name: consumer-ribbon   #消费者名称
  zipkin:
    base-url: http://172.30.105.205:8110
  #通过配置spring.sleuth.sampler.percentage=0.1这个参数来决定了日志记录发送给采集器的概率，0-1交给使用者自己配置。
  #开发阶段和运行初期，一般配置成1全量收集日志,到了上线后可以慢慢降低这一概率。
  sleuth:
    sampler:
      percentage: 1

server:
  port: 8002

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}   #在UI界面以IP注册的形式显示
  client:
    service-url:
      defaultZone: http://admin:admin@regiest01:10010/eureka/,http://admin:admin@regiest02:10020/eureka/,http://admin:admin@regiest03:10030/eureka/

