spring:
  application:
    name: eureka-server   #服务名称
server:
  port: 10020 # 注册中心占用8080端口
eureka:
  instance:
    hostname: regiest02  #实例的主机名(本地访问可以使用localhost)
  client:
    registerWithEureka: false  #设置是否向注册中心注册，默认是true
    fetchRegistry: false    #是否需要去检索寻找服务，默认是true
    serviceUrl:
      defaultZone: http://regiest01:10010/eureka/  #指定注册中心,其实就是 http://localhost:8080/eureka/
