spring:
  application:
    name: eureka-server-ha   #ha服务名称
#  profiles:
#    active: regiest01    #active节点


#配置info信息
info:
  name: regiestry-center
  version: @project.version@
  email: 16050973@qq.com

#配置优雅下线
endpoints:
  #开启节点是否可以访问,sensitive为false不需要授权
  enabled: true
  sensitive: false
  shutdown:
    enabled: true

#取消鉴权
management:
  security:
    enabled: false
