server:
  port: 10030 # 注册中心占用8080端口
eureka:
  instance:
    hostname: regiest03  #实例的主机名(本地访问可以使用localhost)
    prefer-ip-address: true   #开启以ip注册
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}   #在UI界面以IP注册的形式显示
  #    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:admin@regiest02:10020/eureka/,http://admin:admin@regiest01:10010/eureka/  #指定注册中心,其实就是 http://localhost:8080/eureka/
#    registerWithEureka: false  #设置是否向注册中心注册，默认是true
#    fetchRegistry: false    #是否需要去检索寻找服务，默认是true

  server:
    #    eviction-interval-timer-in-ms: 5000  #Eureka服务器清理无效节点的时间间隔，单位：毫秒，缺省：60000，即60秒
    #    use-read-only-response-cache: false  #是否允许开启自我保护模式，缺省：true
    enable-self-preservation: false   #关闭自我保护,缺省：true

security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin