server:
  port: 10020 # 注册中心占用8080端口
eureka:
  instance:
    hostname: regiest02  #实例的主机名(本地访问可以使用localhost)
    prefer-ip-address: true   #开启以ip注册
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}   #在UI界面以IP注册的形式显示
#    instance-id: ${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://admin:admin@regiest01:10010/eureka/,http://admin:admin@regiest03:10030/eureka/  #指定注册中心,其实就是 http://localhost:8080/eureka/
#    registerWithEureka: false  #设置是否向注册中心注册，默认是true
#    fetchRegistry: false    #是否需要去检索寻找服务，默认是true

security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin