spring:
  application:
    name: "service-user"
  zipkin:
    base-url: http://localhost:8110
  sleuth:
    sampler:
      percentage: 1
#  profiles:
#    active: provider01    #active节点

## 说明：注意，从Spring Cloud Dalston开始，Feign默认是不开启Hystrix的。
feign:
  hystrix:
    enabled: false

##运行状态 actuator监控
info:
  app:
    name: service-user
    desc: 用户服务
    email: 16050973@qq.com

endpoints:
  enabled: true
  shutdown:
    enabled: true
#  mappings:
#    sensitive: false

management:
##服务路径
#  context-path: /monitor
##服务端口
#  port: 19111
##取消鉴权
  security:
    enabled: false

