spring:
  application:
    name: config-server
  #配置仓库位置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xianlongbai/springcloud-config
          # 本地仓库目录设定(本地會保留緩存文件)
          basedir: D:/idea_repository/config-cache
          # 本地仓库如果有脏数据，则会强制拉取（默认是false）
          force-pull: true
  #        search-paths: config-repo   #指定的是匹配查询的路径名
  #公共仓库不用配置用户信息
  #        username: *****
  #        password: *****

  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

server:
  port: 18888

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}   #在UI界面以IP注册的形式显示
  client:
    service-url:
      defaultZone: http://admin:admin@regiest01:10010/eureka/,http://admin:admin@regiest02:10020/eureka/,http://admin:admin@regiest03:10030/eureka/
#安全相关
management:
  security:
    enabled: false
