spring:
  application:
    name: service_admin
  boot:
    admin:
      discovery:
        #配置忽略服务
        ignored-services: service_admin
        services: service-provider-demo,consumer-feign
      notify:
        mail:
          enabled: true
          from: 16050973@qq.com
          to: xxx

  #邮件服务配置
  mail:
    host: smtp.qq.com
    username: 16050973@qq.com
    password: xxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 19110

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}   #在UI界面以IP注册的形式显示
  client:
    service-url:
      defaultZone: http://admin:admin@regiest01:10010/eureka/,http://admin:admin@regiest02:10020/eureka/,http://admin:admin@regiest03:10030/eureka/

info:
  name: admin
  version: @project.version@




